[default]
API_URL = "/api"
ACCESS_TOKEN_EXPIRE_MINUTES = 10080
ACCESS_TOKEN_EXPIRE_MINUTES_SENSOR_DEVICES = 259200
ADMIN_USER_ID = "1"
ADMIN_ROLE_NAME = "ADMIN"
ADMIN_ROLE_DESC = "Usuário Administrador do Sistema"
MAIL_SUPPRESS_SEND = 0
MINUTES_TO_CHECK_DEVICES = 60

[production]

[development]

[testing]
MAIL_SUPPRESS_SEND = 1